apiVersion: apps/v1 
kind: Deployment


metadata:
  name: redis-deployment 
  labels:  
    app: myApp  


spec:
  replicas: 1
  selector: 
    matchLabels:
      name: redis-pod
      app: myApp
  template:
    metadata: 
      name: redis-Pod
      labels:
        name: redis-pod
        app: myApp

    spec: 
      containers: 
      - name: redis
        image: docker.elastic.co/elasticsearch/elasticsearch:6.3.2
        ports:
          - containerPort: 6379